# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08226a08ced81bd6c3ba5bcdd72d2f780a8ca2c20e2dc8edac843ba9c88dcc3be2b697483cb341722dde3e844ed541ca5354bc6b211621318d20fef111e3573b

test:
  secret_key_base: 651be56faed23133b669c22ddd6e9379c8d85d8b44744ba3e071493a0709d52ec4599d19209229b9b4d7ebadd3de29cc6ee9c9e3d42dbe176154556c4dc66966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
